### PR TITLE
Added string id 30215

### PR DESCRIPTION
**Pull request by boscorelly**
Please add new strings in english in file next time to let met directly translate it ;)

### CODE REVIEW

**Comment by insertnamehere1** [comment]
The changes were made for id 30215 to the French strings.xml under the comment that the translation was made by Google Translate. You may need to do an git upstream fetch and merge before editing the strings.xml again. It looks like your editing an out of date version.

**Comment by boscorelly** [comment]
My version is the same less the google translate note.

You really can't merge my update ?

How can i update my fork to your last update on the original repo ?

**Comment by insertnamehere1** [comment]
Andrew should have no problem merging this one line. However, I've just submitted a PR that includes 5 more ids in each language file so you should be fetching this to your fork and modifying it when Andrew processes the PR. That way you can merging your changes before the PR to Andrews repo. 

From the clone of your fork, where you do your modifications:
$ git fetch upstream
$ git checkout master
$ get merge upstream/master
$ git push origin

(You may need to update your git config specifying origin and remote)
This will update your fork with any changes that have been made in the upstream (Andrews Repo)

**Comment by boscorelly** [comment]
i have done this and pulled the new.

**Pull request closed without merging**
